version: '3.8'

services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - spark_data:/opt/spark
    ports:
      - "7077:7077"  # Porta do master
      - "8080:8080"  # UI do Spark
      - "8081:8081"  # UI do Worker

volumes:
  spark_data:
